//! Minimal build.rs: reads RUNTIME_REGISTRY.json and generates
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
//! `generated_host_tables.rs` — a set of constants and lookup functions
//! driven by the registry rather than hand-maintained match arms.
//!
//! Adding a new host? Edit `configs/framework/RUNTIME_REGISTRY.json`
//! and rebuild; this file re-generates all tables from the single source of truth.

use std::env;
use std::fs;
use std::path::PathBuf;

/// Escape a string value for safe use inside a Rust `"…"` string literal.
fn rust_str_escape(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let registry_path = manifest_dir
        .join("..")
        .join("..")
        .join("configs/framework/RUNTIME_REGISTRY.json");

    println!("cargo:rerun-if-changed={}", registry_path.display());

    let json_str = fs::read_to_string(&registry_path)
        .unwrap_or_else(|err| panic!("read {}: {err}", registry_path.display()));
    let reg: serde_json::Value =
        serde_json::from_str(&json_str).expect("parse RUNTIME_REGISTRY.json");

    let supported = reg
        .get("host_targets")
        .expect("RUNTIME_REGISTRY missing host_targets")
        .get("supported")
        .and_then(serde_json::Value::as_array)
        .expect("host_targets.supported must be a non-empty array")
        .iter()
        .map(|v| {
            v.as_str()
                .map(str::trim)
                .filter(|s| !s.is_empty())
                .map(str::to_string)
                .expect("non-empty string")
        })
        .collect::<Vec<_>>();

    let metadata = reg
        .get("host_targets")
        .and_then(|v| v.get("metadata"))
        .and_then(serde_json::Value::as_object)
        .expect("host_targets.metadata");

    // ── Generate code ──

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit\n");
    out.push_str("// source: configs/framework/RUNTIME_REGISTRY.json\n\n");

    // --- all_known_host_dirs ---
    let known_dirs = reg
        .get("all_known_host_dirs")
        .and_then(serde_json::Value::as_array);
    if let Some(dirs) = known_dirs {
        let items: Vec<String> = dirs
            .iter()
            .filter_map(|v| v.as_str().map(|s| format!("\"{s}\"")))
            .collect();
        out.push_str(&format!(
            "pub const ALL_KNOWN_HOST_DIRS: &[&str] = &[{}];\n\n",
            items.join(", ")
        ));
    }

    // --- ephemeral_path_patterns ---
    let patterns = reg
        .get("ephemeral_path_patterns")
        .and_then(serde_json::Value::as_array);
    if let Some(pat) = patterns {
        let items: Vec<String> = pat
            .iter()
            .filter_map(|v| v.as_str().map(|s| format!("\"{s}\"")))
            .collect();
        out.push_str(&format!(
            "pub const EPHEMERAL_PATH_PATTERNS: &[&str] = &[{}];\n\n",
            items.join(", ")
        ));
    }

    // --- ephemeral_task_prefixes + is_ephemeral_task_id ---
    let prefixes = reg
        .get("ephemeral_task_prefixes")
        .and_then(serde_json::Value::as_array);
    if let Some(pref) = prefixes {
        let items: Vec<String> = pref
            .iter()
            .filter_map(|v| v.as_str().map(|s| format!("\"{s}\"")))
            .collect();
        out.push_str(&format!(
            "pub const EPHEMERAL_TASK_PREFIXES: &[&str] = &[{}];\n\n",
            items.join(", ")
        ));
        out.push_str(
            "pub fn is_ephemeral_task_id(tid: &str) -> bool {\n\
             EPHEMERAL_TASK_PREFIXES.iter().any(|p| tid.starts_with(p))\n\
             }\n\n",
        );
    } else {
        out.push_str(
            "pub const EPHEMERAL_TASK_PREFIXES: &[&str] = &[];\n\
             pub fn is_ephemeral_task_id(_tid: &str) -> bool { false }\n\n",
        );
    }

    // --- ALL_HOST_IDS (generated from host_targets.supported) ---
    let all_host_ids_items: Vec<String> = supported.iter().map(|id| format!("\"{id}\"")).collect();
    out.push_str(&format!(
        "pub const ALL_HOST_IDS: &[&str] = &[{}];\n\n",
        all_host_ids_items.join(", ")
    ));

    // --- host_home_dirs (from supported host metadata.default_home_dir) ---
    let home_dirs: Vec<String> = supported
        .iter()
        .filter_map(|id| {
            metadata
                .get(id)
                .and_then(|m| m.get("default_home_dir"))
                .and_then(serde_json::Value::as_str)
                .map(|dir| format!("\"{dir}\""))
        })
        .collect();
    out.push_str(&format!(
        "pub fn host_home_dirs() -> &'static [&'static str] {{\n\
         static DIRS: &[&str] = &[{}];\n\
         DIRS\n\
         }}\n\n",
        home_dirs.join(", ")
    ));

    // --- Per-host lookup functions ---
    // Each generates a match arm per supported host, and an empty/fallback default.

    // config_dir → host_private_config_dir
    out.push_str("pub fn host_private_config_dir(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(dir) = metadata
            .get(id.as_str())
            .and_then(|m| m.get("config_dir"))
            .and_then(serde_json::Value::as_str)
        {
            out.push_str(&format!("        \"{id}\" => \"{dir}\",\n"));
        }
    }
    out.push_str("        _ => \"\",\n");
    out.push_str("    }\n}\n\n");

    // projection_entrypoint_subdir
    out.push_str("pub fn projection_entrypoint_subdir(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(dir) = metadata
            .get(id.as_str())
            .and_then(|m| m.get("entrypoint_subdir"))
            .and_then(serde_json::Value::as_str)
            .filter(|s| !s.is_empty())
        {
            out.push_str(&format!("        \"{id}\" => \"{dir}\",\n"));
        }
    }
    out.push_str("        _ => \"rules\",\n");
    out.push_str("    }\n}\n\n");

    // projection_entrypoint_filename
    out.push_str("pub fn projection_entrypoint_filename(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(fname) = metadata
            .get(id.as_str())
            .and_then(|m| m.get("entrypoint_filename"))
            .and_then(serde_json::Value::as_str)
            .filter(|s| !s.is_empty())
        {
            out.push_str(&format!("        \"{id}\" => \"{fname}\",\n"));
        }
    }
    out.push_str("        _ => \"framework.md\",\n");
    out.push_str("    }\n}\n\n");

    // projection_entrypoint_frontmatter_extra
    out.push_str(
        "pub fn projection_entrypoint_frontmatter_extra(host_id: &str) -> &'static str {\n",
    );
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(val) = metadata
            .get(id.as_str())
            .and_then(|m| m.get("entrypoint_frontmatter_extra"))
            .and_then(serde_json::Value::as_str)
            .filter(|s| !s.is_empty())
        {
            let escaped = rust_str_escape(val);
            out.push_str(&format!("        \"{id}\" => \"{escaped}\",\n"));
        }
    }
    out.push_str("        _ => \"\",\n");
    out.push_str("    }\n}\n\n");

    // projection_entrypoint_description
    out.push_str("pub fn projection_entrypoint_description(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(val) = metadata
            .get(id.as_str())
            .and_then(|m| m.get("entrypoint_description"))
            .and_then(serde_json::Value::as_str)
            .filter(|s| !s.is_empty())
        {
            let escaped = rust_str_escape(val);
            out.push_str(&format!("        \"{id}\" => \"{escaped}\",\n"));
        }
    }
    out.push_str("        _ => \"Use this repository's shared framework runtime.\",\n");
    out.push_str("    }\n}\n\n");

    // projection_entrypoint_trailer
    out.push_str("pub fn projection_entrypoint_trailer(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(val) = metadata
            .get(id.as_str())
            .and_then(|m| m.get("entrypoint_trailer"))
            .and_then(serde_json::Value::as_str)
            .filter(|s| !s.is_empty())
        {
            let escaped = rust_str_escape(val);
            out.push_str(&format!("        \"{id}\" => \"{escaped}\",\n"));
        }
    }
    out.push_str("        _ => \"\",\n");
    out.push_str("    }\n}\n\n");

    // review_gate_disable_env
    out.push_str("pub fn review_gate_disable_env(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(env) = metadata
            .get(id.as_str())
            .and_then(|m| m.get("review_gate_disable_env"))
            .and_then(serde_json::Value::as_str)
        {
            out.push_str(&format!("        \"{id}\" => \"{env}\",\n"));
        }
    }
    out.push_str("        _ => \"\",\n");
    out.push_str("    }\n}\n\n");

    // paper_prose_env
    out.push_str("pub fn paper_prose_env(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(env) = metadata
            .get(id.as_str())
            .and_then(|m| m.get("paper_prose_env"))
            .and_then(serde_json::Value::as_str)
        {
            out.push_str(&format!("        \"{id}\" => \"{env}\",\n"));
        }
    }
    out.push_str("        _ => \"\",\n");
    out.push_str("    }\n}\n\n");

    // paper_adversarial_env
    out.push_str("pub fn paper_adversarial_env(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(env) = metadata
            .get(id.as_str())
            .and_then(|m| m.get("paper_adversarial_env"))
            .and_then(serde_json::Value::as_str)
        {
            out.push_str(&format!("        \"{id}\" => \"{env}\",\n"));
        }
    }
    out.push_str("        _ => \"\",\n");
    out.push_str("    }\n}\n\n");

    // settings_guarded_paths
    out.push_str("pub fn settings_guarded_paths(host_id: &str) -> &'static [&'static str] {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(paths) = metadata
            .get(id.as_str())
            .and_then(|m| m.get("settings_paths"))
            .and_then(serde_json::Value::as_array)
        {
            let items: Vec<String> = paths
                .iter()
                .filter_map(|v| v.as_str().map(|s| format!("\"{s}\"")))
                .collect();
            if !items.is_empty() {
                out.push_str(&format!("        \"{id}\" => &[{}],\n", items.join(", ")));
            }
        }
    }
    out.push_str("        _ => &[],\n");
    out.push_str("    }\n}\n\n");

    // generated_entrypoint_paths
    out.push_str("pub fn generated_entrypoint_paths(host_id: &str) -> &'static [&'static str] {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(paths) = metadata
            .get(id.as_str())
            .and_then(|m| m.get("entrypoint_paths"))
            .and_then(serde_json::Value::as_array)
        {
            let items: Vec<String> = paths
                .iter()
                .filter_map(|v| v.as_str().map(|s| format!("\"{s}\"")))
                .collect();
            if !items.is_empty() {
                out.push_str(&format!("        \"{id}\" => &[{}],\n", items.join(", ")));
            }
        }
    }
    out.push_str("        _ => &[],\n");
    out.push_str("    }\n}\n\n");

    // hook_state_unreadable_tag
    out.push_str("pub fn hook_state_unreadable_tag(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(tag) = metadata
            .get(id.as_str())
            .and_then(|m| m.get("hook_state_unreadable_tag"))
            .and_then(serde_json::Value::as_str)
        {
            out.push_str(&format!("        \"{id}\" => \"{tag}\",\n"));
        }
    }
    out.push_str("        _ => \"HOOK_STATE_UNREADABLE\",\n");
    out.push_str("    }\n}\n\n");

    // session_namespace_env
    out.push_str("pub fn session_namespace_env(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(env) = metadata
            .get(id.as_str())
            .and_then(|m| m.get("session_namespace_env"))
            .and_then(serde_json::Value::as_str)
        {
            out.push_str(&format!("        \"{id}\" => \"{env}\",\n"));
        }
    }
    out.push_str("        _ => \"\",\n");
    out.push_str("    }\n}\n\n");

    // home_env_var
    out.push_str("pub fn home_env_var(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(env) = metadata
            .get(id.as_str())
            .and_then(|m| m.get("home_env_var"))
            .and_then(serde_json::Value::as_str)
        {
            out.push_str(&format!("        \"{id}\" => \"{env}\",\n"));
        }
    }
    out.push_str("        _ => \"\",\n");
    out.push_str("    }\n}\n\n");

    // install_scopes — returns &'static [&'static str] for a host_id
    out.push_str("pub fn install_scopes(host_id: &str) -> &'static [&'static str] {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(arr) = metadata
            .get(id.as_str())
            .and_then(|m| m.get("install_scopes"))
            .and_then(serde_json::Value::as_array)
        {
            let items: Vec<String> = arr
                .iter()
                .filter_map(|v| v.as_str().map(|s| format!("\"{s}\"")))
                .collect();
            if !items.is_empty() {
                out.push_str(&format!("        \"{id}\" => &[{}],\n", items.join(", ")));
            }
        }
    }
    out.push_str("        _ => &[\"project\"],\n");
    out.push_str("    }\n}\n\n");

    // --- host_projection_mcp_relative (from host_projections.*.mcp_config_paths) ---
    {
        let projections = reg
            .get("host_projections")
            .and_then(|v| v.as_object())
            .expect("RUNTIME_REGISTRY missing host_projections");

        out.push_str("/// Return the relative MCP config path for a (host_id, scope) pair.\n");
        out.push_str("/// Returns `\"\"` if no matching entry is found.\n");
        out.push_str("/// Source: host_projections.*.mcp_config_paths[].relative\n");
        out.push_str(
            "pub fn host_projection_mcp_relative(host_id: &str, scope: &str) -> &'static str {\n",
        );
        out.push_str("    match (host_id, scope) {\n");
        for host_id in &supported {
            if let Some(entries) = projections
                .get(host_id.as_str())
                .and_then(|p| p.get("mcp_config_paths"))
                .and_then(|v| v.as_array())
            {
                for entry in entries {
                    if let (Some(s), Some(rel)) = (
                        entry.get("scope").and_then(|v| v.as_str()),
                        entry.get("relative").and_then(|v| v.as_str()),
                    ) {
                        let escaped = rust_str_escape(rel);
                        out.push_str(&format!(
                            "        (\"{host_id}\", \"{s}\") => \"{escaped}\",\n"
                        ));
                    }
                }
            }
        }
        out.push_str("        _ => \"\",\n");
        out.push_str("    }\n}\n\n");
    }

    // --- host_projection_mcp_base_is_account (from host_projections.*.mcp_config_paths) ---
    {
        let projections = reg
            .get("host_projections")
            .and_then(|v| v.as_object())
            .expect("RUNTIME_REGISTRY missing host_projections");

        out.push_str(
            "/// Returns `true` when the matching mcp_config_paths entry uses `account_home` base.\n",
        );
        out.push_str(
            "/// This signals the caller to resolve the path relative to `account_home_root`\n",
        );
        out.push_str("/// instead of `host_home_root`.\n");
        out.push_str("#[allow(clippy::match_like_matches_macro)]\n");
        out.push_str(
            "pub fn host_projection_mcp_base_is_account(host_id: &str, scope: &str) -> bool {\n",
        );
        out.push_str("    match (host_id, scope) {\n");
        for host_id in &supported {
            if let Some(entries) = projections
                .get(host_id.as_str())
                .and_then(|p| p.get("mcp_config_paths"))
                .and_then(|v| v.as_array())
            {
                for entry in entries {
                    if let Some(s) = entry.get("scope").and_then(|v| v.as_str()) {
                        let is_account =
                            entry.get("base").and_then(|v| v.as_str()) == Some("account_home");
                        if is_account {
                            out.push_str(&format!("        (\"{host_id}\", \"{s}\") => true,\n"));
                        }
                    }
                }
            }
        }
        out.push_str("        _ => false,\n");
        out.push_str("    }\n}\n\n");
    }

    // --- host_mcp_config_format (from host_targets.metadata.*.mcp_config_format) ---
    {
        out.push_str("/// Return the MCP config JSON key format for a host: \"snake_case\" or \"camelCase\".\n");
        out.push_str("/// Returns \"camelCase\" as default if not specified.\n");
        out.push_str("/// Source: host_targets.metadata.*.mcp_config_format\n");
        out.push_str("pub fn host_mcp_config_format(host_id: &str) -> &'static str {\n");
        out.push_str("    match host_id {\n");
        for id in &supported {
            if let Some(fmt) = metadata
                .get(id.as_str())
                .and_then(|m| m.get("mcp_config_format"))
                .and_then(serde_json::Value::as_str)
                .filter(|s| !s.is_empty())
            {
                out.push_str(&format!("        \"{id}\" => \"{fmt}\",\n"));
            }
        }
        out.push_str("        _ => \"camelCase\",\n");
        out.push_str("    }\n}\n\n");
    }

    // --- host_driver_binary (from host_targets.metadata.*.driver_binary) ---
    out.push_str("/// Return the driver binary name for a host.\n");
    out.push_str("/// Returns \"\" if not specified in registry.\n");
    out.push_str("/// Source: host_targets.metadata.*.driver_binary\n");
    out.push_str("pub fn host_driver_binary(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(bin) = metadata
            .get(id.as_str())
            .and_then(|m| m.get("driver_binary"))
            .and_then(serde_json::Value::as_str)
        {
            out.push_str(&format!("        \"{id}\" => \"{bin}\",\n"));
        }
    }
    out.push_str("        _ => \"\",\n");
    out.push_str("    }\n}\n\n");

    // --- host_config_schema_url (from host_targets.metadata.*.config_schema_url) ---
    out.push_str("/// Return the config schema URL for a host (e.g. TOML config schema).\n");
    out.push_str("/// Returns \"\" if not specified.\n");
    out.push_str("/// Source: host_targets.metadata.*.config_schema_url\n");
    out.push_str("pub fn host_config_schema_url(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(url) = metadata
            .get(id.as_str())
            .and_then(|m| m.get("config_schema_url"))
            .and_then(serde_json::Value::as_str)
        {
            out.push_str(&format!("        \"{id}\" => \"{url}\",\n"));
        }
    }
    out.push_str("        _ => \"\",\n");
    out.push_str("    }\n}\n\n");

    // --- ALL_HOST_WORKSPACE_ROOT_ENV_VARS (from hook_launcher.root_env_var) ---
    {
        let env_vars: Vec<String> = supported
            .iter()
            .filter_map(|id| {
                metadata
                    .get(id.as_str())
                    .and_then(|m| m.get("hook_launcher"))
                    .and_then(|hl| hl.get("root_env_var"))
                    .and_then(serde_json::Value::as_str)
                    .map(|ev| format!("\"{ev}\""))
            })
            .collect();
        out.push_str(&format!(
            "/// All known host workspace/project root env vars from the registry.\n\
             pub const ALL_HOST_WORKSPACE_ROOT_ENV_VARS: &[&str] = &[{}];\n\n",
            env_vars.join(", ")
        ));
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    // --- stdio_op_domains ---
    let mut stdio_out = String::new();
    stdio_out.push_str("// @generated by build.rs — do not edit\n");
    stdio_out.push_str("// source: configs/framework/RUNTIME_REGISTRY.json stdio_op_domains\n\n");

    let stdio_domains = reg
        .get("stdio_op_domains")
        .and_then(serde_json::Value::as_object)
        .expect("RUNTIME_REGISTRY missing stdio_op_domains");

    // Build the match arms for classify_stdio_op_registry
    stdio_out.push_str("/// Classify a stdio operation string into its domain name.\n");
    stdio_out.push_str("/// Returns `Some(domain_name)` for known ops, `None` for unknown.\n");
    stdio_out.push_str("pub fn classify_stdio_op_registry(op: &str) -> Option<&'static str> {\n");
    stdio_out.push_str("    match op {\n");
    let mut domain_order = Vec::new();
    for (domain_name, ops_val) in stdio_domains {
        let ops: Vec<String> = ops_val
            .as_array()
            .expect("stdio_op_domains value must be an array")
            .iter()
            .map(|v| v.as_str().expect("stdio op must be a string").to_string())
            .collect();
        domain_order.push((domain_name.clone(), ops));
    }
    for (domain_name, ops) in &domain_order {
        stdio_out.push_str(&format!("        // {domain_name} ops\n"));
        let arms: Vec<String> = ops.iter().map(|op| format!("\"{op}\"")).collect();
        stdio_out.push_str(&format!(
            "        {} => Some(\"{domain_name}\"),\n",
            arms.join(" | ")
        ));
    }
    stdio_out.push_str("        _ => None,\n");
    stdio_out.push_str("    }\n}\n\n");

    // Build the STDIO_OP_DOMAINS const
    stdio_out.push_str("/// All known stdio operation strings grouped by domain.\n");
    stdio_out.push_str("pub const STDIO_OP_DOMAINS: &[(&str, &[&str])] = &[\n");
    for (domain_name, ops) in &domain_order {
        let items: Vec<String> = ops.iter().map(|op| format!("\"{op}\"")).collect();
        stdio_out.push_str(&format!(
            "    (\"{domain_name}\", &[{}]),\n",
            items.join(", ")
        ));
    }
    stdio_out.push_str("];\n");

    fs::write(out_dir.join("generated_stdio_tables.rs"), &stdio_out)
        .expect("write generated_stdio_tables.rs");

    fs::write(out_dir.join("generated_host_tables.rs"), out)
        .expect("write generated_host_tables.rs");
}
