//! Minimal build.rs: reads RUNTIME_REGISTRY.json and generates
//! `generated_host_tables.rs` — a set of constants and lookup functions
//! driven by the registry rather than hand-maintained match arms.
//!
//! Adding a new host? Edit `configs/framework/RUNTIME_REGISTRY.json`
//! and rebuild; this file re-generates all tables from the single source of truth.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let registry_path = manifest_dir
        .join("..")
        .join("..")
        .join("configs/framework/RUNTIME_REGISTRY.json");

    println!("cargo:rerun-if-changed={}", registry_path.display());

    let json_str = fs::read_to_string(&registry_path)
        .unwrap_or_else(|err| panic!("read {}: {err}", registry_path.display()));
    let reg: serde_json::Value =
        serde_json::from_str(&json_str).expect("parse RUNTIME_REGISTRY.json");

    let supported = reg
        .get("host_targets")
        .expect("RUNTIME_REGISTRY missing host_targets")
        .get("supported")
        .and_then(serde_json::Value::as_array)
        .expect("host_targets.supported must be a non-empty array")
        .iter()
        .map(|v| {
            v.as_str()
                .map(str::trim)
                .filter(|s| !s.is_empty())
                .map(str::to_string)
                .expect("non-empty string")
        })
        .collect::<Vec<_>>();

    let metadata = reg
        .get("host_targets")
        .and_then(|v| v.get("metadata"))
        .and_then(serde_json::Value::as_object)
        .expect("host_targets.metadata");

    // ── Generate code ──

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit\n");
    out.push_str("// source: configs/framework/RUNTIME_REGISTRY.json\n\n");

    // --- all_known_host_dirs ---
    let known_dirs = reg.get("all_known_host_dirs").and_then(serde_json::Value::as_array);
    if let Some(dirs) = known_dirs {
        let items: Vec<String> = dirs.iter()
            .filter_map(|v| v.as_str().map(|s| format!("\"{s}\"")))
            .collect();
        out.push_str(&format!(
            "pub const ALL_KNOWN_HOST_DIRS: &[&str] = &[{}];\n\n",
            items.join(", ")
        ));
    }

    // --- ephemeral_path_patterns ---
    let patterns = reg.get("ephemeral_path_patterns").and_then(serde_json::Value::as_array);
    if let Some(pat) = patterns {
        let items: Vec<String> = pat.iter()
            .filter_map(|v| v.as_str().map(|s| format!("\"{s}\"")))
            .collect();
        out.push_str(&format!(
            "pub const EPHEMERAL_PATH_PATTERNS: &[&str] = &[{}];\n\n",
            items.join(", ")
        ));
    }

    // --- ephemeral_task_prefixes + is_ephemeral_task_id ---
    let prefixes = reg.get("ephemeral_task_prefixes").and_then(serde_json::Value::as_array);
    if let Some(pref) = prefixes {
        let items: Vec<String> = pref.iter()
            .filter_map(|v| v.as_str().map(|s| format!("\"{s}\"")))
            .collect();
        out.push_str(&format!(
            "pub const EPHEMERAL_TASK_PREFIXES: &[&str] = &[{}];\n\n",
            items.join(", ")
        ));
        out.push_str(
            "pub fn is_ephemeral_task_id(tid: &str) -> bool {\n\
             EPHEMERAL_TASK_PREFIXES.iter().any(|p| tid.starts_with(p))\n\
             }\n\n"
        );
    } else {
        out.push_str(
            "pub const EPHEMERAL_TASK_PREFIXES: &[&str] = &[];\n\
             pub fn is_ephemeral_task_id(_tid: &str) -> bool { false }\n\n"
        );
    }

    // --- ALL_HOST_IDS (generated from host_targets.supported) ---
    let all_host_ids_items: Vec<String> = supported.iter().map(|id| format!("\"{id}\"")).collect();
    out.push_str(&format!(
        "pub const ALL_HOST_IDS: &[&str] = &[{}];\n\n",
        all_host_ids_items.join(", ")
    ));

    // --- host_home_dirs (from supported host metadata.default_home_dir) ---
    let home_dirs: Vec<String> = supported.iter()
        .filter_map(|id| {
            metadata.get(id)
                .and_then(|m| m.get("default_home_dir"))
                .and_then(serde_json::Value::as_str)
                .map(|dir| format!("\"{dir}\""))
        })
        .collect();
    out.push_str(&format!(
        "pub fn host_home_dirs() -> &'static [&'static str] {{\n\
         static DIRS: &[&str] = &[{}];\n\
         DIRS\n\
         }}\n\n",
        home_dirs.join(", ")
    ));

    // --- Per-host lookup functions ---
    // Each generates a match arm per supported host, and an empty/fallback default.

    // config_dir → host_private_config_dir
    out.push_str("pub fn host_private_config_dir(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(dir) = metadata.get(id.as_str())
            .and_then(|m| m.get("config_dir"))
            .and_then(serde_json::Value::as_str)
        {
            out.push_str(&format!("        \"{id}\" => \"{dir}\",\n"));
        }
    }
    out.push_str("        _ => \"\",\n");
    out.push_str("    }\n}\n\n");

    // review_gate_disable_env
    out.push_str("pub fn review_gate_disable_env(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(env) = metadata.get(id.as_str())
            .and_then(|m| m.get("review_gate_disable_env"))
            .and_then(serde_json::Value::as_str)
        {
            out.push_str(&format!("        \"{id}\" => \"{env}\",\n"));
        }
    }
    out.push_str("        _ => \"\",\n");
    out.push_str("    }\n}\n\n");

    // paper_prose_env
    out.push_str("pub fn paper_prose_env(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(env) = metadata.get(id.as_str())
            .and_then(|m| m.get("paper_prose_env"))
            .and_then(serde_json::Value::as_str)
        {
            out.push_str(&format!("        \"{id}\" => \"{env}\",\n"));
        }
    }
    out.push_str("        _ => \"\",\n");
    out.push_str("    }\n}\n\n");

    // paper_adversarial_env
    out.push_str("pub fn paper_adversarial_env(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(env) = metadata.get(id.as_str())
            .and_then(|m| m.get("paper_adversarial_env"))
            .and_then(serde_json::Value::as_str)
        {
            out.push_str(&format!("        \"{id}\" => \"{env}\",\n"));
        }
    }
    out.push_str("        _ => \"\",\n");
    out.push_str("    }\n}\n\n");

    // settings_guarded_paths
    out.push_str("pub fn settings_guarded_paths(host_id: &str) -> &'static [&'static str] {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(paths) = metadata.get(id.as_str())
            .and_then(|m| m.get("settings_paths"))
            .and_then(serde_json::Value::as_array)
        {
            let items: Vec<String> = paths.iter()
                .filter_map(|v| v.as_str().map(|s| format!("\"{s}\"")))
                .collect();
            if !items.is_empty() {
                out.push_str(&format!(
                    "        \"{id}\" => &[{}],\n",
                    items.join(", ")
                ));
            }
        }
    }
    out.push_str("        _ => &[],\n");
    out.push_str("    }\n}\n\n");

    // generated_entrypoint_paths
    out.push_str("pub fn generated_entrypoint_paths(host_id: &str) -> &'static [&'static str] {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(paths) = metadata.get(id.as_str())
            .and_then(|m| m.get("entrypoint_paths"))
            .and_then(serde_json::Value::as_array)
        {
            let items: Vec<String> = paths.iter()
                .filter_map(|v| v.as_str().map(|s| format!("\"{s}\"")))
                .collect();
            if !items.is_empty() {
                out.push_str(&format!(
                    "        \"{id}\" => &[{}],\n",
                    items.join(", ")
                ));
            }
        }
    }
    out.push_str("        _ => &[],\n");
    out.push_str("    }\n}\n\n");

    // hook_state_unreadable_tag
    out.push_str("pub fn hook_state_unreadable_tag(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(tag) = metadata.get(id.as_str())
            .and_then(|m| m.get("hook_state_unreadable_tag"))
            .and_then(serde_json::Value::as_str)
        {
            out.push_str(&format!("        \"{id}\" => \"{tag}\",\n"));
        }
    }
    out.push_str("        _ => \"HOOK_STATE_UNREADABLE\",\n");
    out.push_str("    }\n}\n\n");

    // session_namespace_env
    out.push_str("pub fn session_namespace_env(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(env) = metadata.get(id.as_str())
            .and_then(|m| m.get("session_namespace_env"))
            .and_then(serde_json::Value::as_str)
        {
            out.push_str(&format!("        \"{id}\" => \"{env}\",\n"));
        }
    }
    out.push_str("        _ => \"\",\n");
    out.push_str("    }\n}\n\n");

    // home_env_var
    out.push_str("pub fn home_env_var(host_id: &str) -> &'static str {\n");
    out.push_str("    match host_id {\n");
    for id in &supported {
        if let Some(env) = metadata.get(id.as_str())
            .and_then(|m| m.get("home_env_var"))
            .and_then(serde_json::Value::as_str)
        {
            out.push_str(&format!("        \"{id}\" => \"{env}\",\n"));
        }
    }
    out.push_str("        _ => \"\",\n");
    out.push_str("    }\n}\n\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("generated_host_tables.rs"), out)
        .expect("write generated_host_tables.rs");
}
