#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: check_tikz_figure.sh <figure.tex> [--strict]

Lightweight checks for paper-ready TikZ standalone figures.
Exit codes: 0 pass, 1 warnings in --strict mode, 2 errors.
USAGE
}

if [[ $# -lt 1 ]]; then
  usage
  exit 2
fi

tex_file=$1
shift
strict=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --strict)
      strict=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ ! -f "$tex_file" ]]; then
  echo "Missing TeX file: $tex_file" >&2
  exit 2
fi

errors=()
warnings=()

contains() {
  grep -Eq "$1" "$tex_file"
}

if ! contains '\\documentclass(\[[^]]*\])?\{standalone\}'; then
  errors+=("Use the standalone class for cropped paper figure output.")
fi

if ! contains '\\begin\{tikzpicture\}' || ! contains '\\end\{tikzpicture\}'; then
  errors+=("The file must contain a tikzpicture environment.")
fi

if contains '\\begin\{figure\*?\}' || contains '\\end\{figure\*?\}'; then
  errors+=("Do not put a figure environment inside the standalone asset.")
fi

if contains '\\caption'; then
  warnings+=("Keep captions outside the standalone file.")
fi

if contains '\b(Fig\.|Figure[[:space:]]+[0-9]+|图[[:space:]]*[0-9]+)'; then
  warnings+=("Do not draw figure numbers or Fig. labels inside the canvas.")
fi

if contains '\\includegraphics'; then
  warnings+=("Avoid embedding the raster draft in the final TikZ asset.")
fi

if contains '(prompt|negative prompt|seed|generated by|AI-generated)'; then
  warnings+=("Remove AI prompt or generation metadata from the figure.")
fi

if contains '\\section|\\maketitle'; then
  warnings+=("This looks like a document, not a standalone figure asset.")
fi

if grep -Eq '[一-龯]' "$tex_file" && contains 'rotate[[:space:]]*=[[:space:]]*90'; then
  warnings+=("Do not rotate CJK labels; xelatex often renders them poorly.")
fi

if grep -Eq '\\documentclass\[[^]]*border[[:space:]]*=[[:space:]]*([1-9][1-9]|[0-9]{3,})[[:space:]]*pt[^]]*\]\{standalone\}' "$tex_file"; then
  warnings+=("Use a small border by default; large borders waste paper space.")
fi

if ((${#errors[@]} > 0)); then
  echo "ERRORS:"
  for item in "${errors[@]}"; do
    echo "- $item"
  done
fi

if ((${#warnings[@]} > 0)); then
  echo "WARNINGS:"
  for item in "${warnings[@]}"; do
    echo "- $item"
  done
fi

if ((${#errors[@]} == 0 && ${#warnings[@]} == 0)); then
  echo "PASS: TikZ standalone checks passed."
fi

if ((${#errors[@]} > 0)); then
  exit 2
fi

if ((strict == 1 && ${#warnings[@]} > 0)); then
  exit 1
fi

exit 0

