//! Compile-time HostProvider registration from `RUNTIME_REGISTRY.json` → `host_targets.host_providers`.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let registry_path = manifest_dir
        .join("..")
        .join("..")
        .join("configs/framework/RUNTIME_REGISTRY.json");
    let hosts_mod_path = manifest_dir.join("src/hosts/mod.rs");
    let cargo_toml_path = manifest_dir.join("Cargo.toml");

    println!("cargo:rerun-if-changed={}", registry_path.display());
    println!("cargo:rerun-if-changed={}", hosts_mod_path.display());
    println!("cargo:rerun-if-changed={}", cargo_toml_path.display());

    let json_str = fs::read_to_string(&registry_path)
        .unwrap_or_else(|err| panic!("read {}: {err}", registry_path.display()));
    let reg: serde_json::Value =
        serde_json::from_str(&json_str).expect("parse RUNTIME_REGISTRY.json");

    let hosts_mod = fs::read_to_string(&hosts_mod_path)
        .unwrap_or_else(|err| panic!("read {}: {err}", hosts_mod_path.display()));
    let cargo_toml = fs::read_to_string(&cargo_toml_path)
        .unwrap_or_else(|err| panic!("read {}: {err}", cargo_toml_path.display()));

    let host_targets = reg
        .get("host_targets")
        .expect("RUNTIME_REGISTRY missing host_targets");
    let supported: Vec<String> = host_targets
        .get("supported")
        .and_then(serde_json::Value::as_array)
        .expect("host_targets.supported must be a non-empty array")
        .iter()
        .map(|value| {
            value
                .as_str()
                .map(str::trim)
                .filter(|s| !s.is_empty())
                .map(str::to_string)
                .expect("host_targets.supported entries must be non-empty strings")
        })
        .collect();
    assert!(
        !supported.is_empty(),
        "host_targets.supported must not be empty"
    );

    let providers = host_targets
        .get("host_providers")
        .and_then(serde_json::Value::as_object)
        .expect("host_targets.host_providers must be an object");

    for host_id in &supported {
        if !providers.contains_key(host_id) {
            panic!(
                "host_targets.host_providers missing entry for supported host `{host_id}`"
            );
        }
    }
    for host_id in providers.keys() {
        if !supported.iter().any(|id| id == host_id) {
            panic!(
                "host_targets.host_providers has `{host_id}` which is not in host_targets.supported"
            );
        }
    }

    let mut pushes = String::new();
    for host_id in &supported {
        let entry = providers
            .get(host_id)
            .and_then(serde_json::Value::as_object)
            .unwrap_or_else(|| panic!("host_providers.{host_id} must be an object"));
        let feature = entry
            .get("cargo_feature")
            .and_then(serde_json::Value::as_str)
            .unwrap_or_else(|| panic!("host_providers.{host_id}.cargo_feature required"));
        let module = entry
            .get("provider_module")
            .and_then(serde_json::Value::as_str)
            .unwrap_or_else(|| panic!("host_providers.{host_id}.provider_module required"));
        let provider_type = entry
            .get("provider_type")
            .and_then(serde_json::Value::as_str)
            .unwrap_or_else(|| panic!("host_providers.{host_id}.provider_type required"));

        validate_host_provider_mod_declarations(
            host_id,
            feature,
            module,
            entry
                .get("hooks_module")
                .and_then(serde_json::Value::as_str),
            &hosts_mod,
            &cargo_toml,
        );

        pushes.push_str(&format!(
            "    #[cfg(feature = \"{feature}\")]\n    providers.push(Box::new(super::{module}::{provider_type}));\n"
        ));
    }

    let ids_literal = supported
        .iter()
        .map(|id| format!("\"{id}\""))
        .collect::<Vec<_>>()
        .join(", ");

    let generated = format!(
        r#"// @generated by build.rs — do not edit
// source: configs/framework/RUNTIME_REGISTRY.json → host_targets.host_providers

pub(crate) const REGISTRY_SUPPORTED_HOST_IDS: &[&str] = &[{ids_literal}];

pub(crate) fn push_registered_host_providers(
    providers: &mut Vec<Box<dyn super::HostProvider>>,
) {{
{pushes}}}
"#
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("generated_host_providers.rs"), generated)
        .expect("write generated_host_providers.rs");
}

fn validate_host_provider_mod_declarations(
    host_id: &str,
    cargo_feature: &str,
    provider_module: &str,
    hooks_module: Option<&str>,
    hosts_mod_rs: &str,
    cargo_toml: &str,
) {
    if !cargo_toml_declares_feature(cargo_toml, cargo_feature) {
        panic!(
            "host_providers.{host_id}: Cargo.toml [features] missing `{cargo_feature}`; \
             add it manually (features are not generated from RUNTIME_REGISTRY.json)"
        );
    }

    if !hosts_mod_has_cfg_provider(hosts_mod_rs, cargo_feature, provider_module) {
        panic!(
            "host_providers.{host_id}: expected `#[cfg(feature = \"{cargo_feature}\")] mod {provider_module};` \
             in core/router-rs/src/hosts/mod.rs (registry provider_module / cargo_feature mismatch)"
        );
    }

    if let Some(hooks) = hooks_module {
        if !hosts_mod_declares_module(hosts_mod_rs, hooks) {
            panic!(
                "host_providers.{host_id}: expected `mod {hooks}` or `pub mod {hooks}` \
                 in core/router-rs/src/hosts/mod.rs (registry hooks_module mismatch)"
            );
        }
    }
}

fn cargo_toml_declares_feature(cargo_toml: &str, feature: &str) -> bool {
    let needle = format!("{feature} =");
    cargo_toml
        .lines()
        .any(|line| line.trim().starts_with(&needle))
}

fn hosts_mod_has_cfg_provider(hosts_mod_rs: &str, cargo_feature: &str, provider_module: &str) -> bool {
    let cfg_needle = format!(r#"cfg(feature = "{cargo_feature}")"#);
    let mod_needle = format!("mod {provider_module}");
    let lines: Vec<&str> = hosts_mod_rs.lines().collect();
    for (index, line) in lines.iter().enumerate() {
        if !line.contains(&cfg_needle) {
            continue;
        }
        let window_end = (index + 3).min(lines.len());
        let window = lines[index..window_end].join("\n");
        if window.contains(&mod_needle) {
            return true;
        }
    }
    false
}

fn hosts_mod_declares_module(hosts_mod_rs: &str, module: &str) -> bool {
    let mod_needle = format!("mod {module}");
    hosts_mod_rs
        .lines()
        .any(|line| line.contains(&mod_needle))
}
