//! Build.rs for host-projection: generates host provider struct definitions,
//! trait implementations, and the provider registry from RUNTIME_REGISTRY.json.
//!
//! Adding a new host? Edit `configs/framework/RUNTIME_REGISTRY.json`
//! and rebuild; all provider code is generated from the single source of truth.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let registry_path = manifest_dir
        .join("..")
        .join("..")
        .join("configs/framework/RUNTIME_REGISTRY.json");

    println!("cargo:rerun-if-changed={}", registry_path.display());

    let json_str = fs::read_to_string(&registry_path)
        .unwrap_or_else(|err| panic!("read {}: {err}", registry_path.display()));
    let reg: serde_json::Value =
        serde_json::from_str(&json_str).expect("parse RUNTIME_REGISTRY.json");

    let supported: Vec<String> = reg
        .get("host_targets")
        .expect("RUNTIME_REGISTRY missing host_targets")
        .get("supported")
        .and_then(serde_json::Value::as_array)
        .expect("host_targets.supported must be a non-empty array")
        .iter()
        .map(|v| {
            v.as_str()
                .map(str::trim)
                .filter(|s| !s.is_empty())
                .map(str::to_string)
                .expect("non-empty string")
        })
        .collect();

    let metadata = reg
        .get("host_targets")
        .and_then(|v| v.get("metadata"))
        .and_then(serde_json::Value::as_object)
        .expect("host_targets.metadata");

    let nl = "\n";

    // Helper: extract string field from metadata
    let meta_str = |id: &str, field: &str| -> String {
        metadata
            .get(id)
            .and_then(|m| m.get(field))
            .and_then(serde_json::Value::as_str)
            .map(|s| s.to_string())
            .unwrap_or_default()
    };

    // Helper: extract bool field from metadata
    let meta_bool = |id: &str, field: &str| -> bool {
        metadata
            .get(id)
            .and_then(|m| m.get(field))
            .and_then(serde_json::Value::as_bool)
            .unwrap_or(false)
    };

    // Helper: extract string array from metadata
    let meta_arr = |id: &str, field: &str| -> Vec<String> {
        metadata
            .get(id)
            .and_then(|m| m.get(field))
            .and_then(serde_json::Value::as_array)
            .map(|arr| arr.iter().filter_map(|v| v.as_str().map(|s| s.to_string())).collect())
            .unwrap_or_default()
    };

    // Helper: PascalCase name
    fn pascal(id: &str) -> String {
        let mut chars = id.chars();
        match chars.next() {
            Some(c) => c.to_uppercase().to_string() + chars.as_str(),
            None => id.to_string(),
        }
    }

    let mut out = String::new();

    // Preamble
    out.push_str("// @generated by build.rs from configs/framework/RUNTIME_REGISTRY.json\n");
    out.push_str("// HostProvider structs and trait impls -- do not edit manually.\n\n");

    // ── Helper: render a JSON string array as a Rust array literal ──
    fn render_arr(items: &[String]) -> String {
        if items.is_empty() {
            return "&[]".to_string();
        }
        let inner: Vec<String> = items.iter().map(|s| format!("\"{}\"", s)).collect();
        format!("&[{}]", inner.join(", "))
    }

    // ── Struct definitions ──
    for id in &supported {
        out.push_str(&format!("pub struct {}HostProvider;\n", pascal(id)));
    }
    out.push('\n');

    // ── HostToolExecutor (empty, all hosts) ──
    for id in &supported {
        out.push_str(&format!("impl HostToolExecutor for {}HostProvider {{}}\n", pascal(id)));
    }
    out.push('\n');

    // ── HostLifecycle ──
    for id in &supported {
        let sn = format!("{}HostProvider", pascal(id));

        // Build method overrides
        let mut methods = String::new();
        methods.push_str(&format!(
            "{}    fn profile_id(&self) -> &'static str {{ \"{}\" }}", nl, meta_str(id, "profile_id")
        ));
        methods.push_str(&format!(
            "{}    fn session_supervisor_driver(&self) -> &'static str {{ \"{}\" }}", nl, meta_str(id, "session_supervisor_driver")
        ));
        methods.push_str(&format!(
            "{}    fn context_file(&self) -> &'static str {{ \"{}\" }}", nl, meta_str(id, "context_file")
        ));
        methods.push_str(&format!(
            "{}    fn driver_binary(&self) -> &'static str {{ \"{}\" }}", nl, meta_str(id, "driver_binary")
        ));
        methods.push_str(&format!(
            "{}    fn driver_supports_resume(&self) -> bool {{ {} }}", nl, meta_bool(id, "driver_supports_resume")
        ));

        let hooks_path = meta_str(id, "hooks_manifest_path");
        if !hooks_path.is_empty() {
            methods.push_str(&format!(
                "{}    fn hooks_manifest_path(&self) -> Option<&'static str> {{ Some(\"{}\") }}", nl, hooks_path
            ));
        }

        let review_types = meta_arr(id, "subagent_review_types");
        if !review_types.is_empty() {
            methods.push_str(&format!(
                "{}    fn subagent_review_types(&self) -> &'static [&'static str] {{ {} }}",
                nl, render_arr(&review_types)
            ));
        }

        let events = meta_arr(id, "registered_hook_events");
        if !events.is_empty() {
            methods.push_str(&format!(
                "{}    fn registered_hook_events(&self) -> &'static [&'static str] {{ {} }}",
                nl, render_arr(&events)
            ));
        }

        // build_driver_args override
        if meta_bool(id, "override_build_driver_args") {
            methods.push_str(&format!(
                "{0}    fn build_driver_args(\
                 {0}        &self, cwd: &str, prompt: Option<&str>,\
                 {0}        resume_target: Option<&str>, resume_mode: &str, resume_only: bool,\
                 {0}    ) -> Option<(Vec<String>, String)> {{\
                 {0}        super::capability_overrides::host_build_driver_args(\
                 \"{id}\", cwd, prompt, resume_target, resume_mode, resume_only)\
                 {0}    }}", nl
            ));
        }

        out.push_str(&format!("impl HostLifecycle for {sn} {{{methods}{nl}}}{nl}", methods = methods));
    }

    // ── HostTelemetry ──
    for id in &supported {
        let sn = format!("{}HostProvider", pascal(id));
        let mut methods = String::new();
        methods.push_str(&format!(
            "{}    fn hook_telemetry_surface(&self) -> &'static str {{ \"{}\" }}", nl, meta_str(id, "hook_telemetry_surface")
        ));

        let obs = meta_str(id, "observation_host_id");
        if !obs.is_empty() {
            methods.push_str(&format!(
                "{}    fn observation_host_id(&self) -> Option<&'static str> {{ Some(\"{}\") }}", nl, obs
            ));
        }

        // Generate observation surface extraction from registry fields.
        let obs_followup_keys = meta_arr(id, "observation_followup_keys");
        let obs_additional_pointer = meta_str(id, "observation_additional_pointer");
        let obs_additional_fallback = meta_str(id, "observation_additional_fallback_key");

        if !obs_followup_keys.is_empty() {
            // Build followup key chain: output.get("k1").or_else(|| output.get("k2"))...
            let key_checks: String = obs_followup_keys.iter().map(|k| {
                format!("output.get(\"{k}\")")
            }).collect::<Vec<_>>().join(".or_else(|| ");
            let close_parens: String = (0..obs_followup_keys.len() - 1).map(|_| ')').collect();
            let key_chain = format!("{key_checks}{close_parens}.and_then(serde_json::Value::as_str).map(|s| s.to_string())");

            // Build additional extraction
            let additional = if obs_additional_fallback.is_empty() || obs_additional_fallback == "null" {
                format!("output.pointer(\"{obs_additional_pointer}\").and_then(serde_json::Value::as_str).map(|s| s.to_string())")
            } else {
                format!("output.pointer(\"{obs_additional_pointer}\").or_else(|| output.get(\"{obs_additional_fallback}\")).and_then(serde_json::Value::as_str).map(|s| s.to_string())")
            };

            methods.push_str(&format!(
                "{0}    fn extract_observation_surfaces(&self, output: &serde_json::Value) -> (Option<String>, Option<String>) {{\
                 {0}        let followup = {1};\
                 {0}        let additional = {2};\
                 {0}        (followup, additional)\
                 {0}    }}", nl, key_chain, additional
            ));
        }

        out.push_str(&format!("impl HostTelemetry for {sn} {{{methods}{nl}}}{nl}", methods = methods));
    }

    // ── HostProvider ──
    for id in &supported {
        let sn = format!("{}HostProvider", pascal(id));
        let tool = meta_str(id, "install_tool");
        let mcp = meta_str(id, "mcp_config_key");
        let trans = meta_str(id, "transport_type");
        let cfg = meta_str(id, "config_path");

        let caps = vec![
            ("batch_execution", meta_bool(id, "batch_execution")),
            ("cron_execution", meta_bool(id, "cron_execution")),
            ("ci_runner", meta_bool(id, "ci_runner")),
            ("non_interactive_entrypoint", meta_bool(id, "non_interactive_entrypoint")),
            ("external_session_supervisor", meta_bool(id, "external_session_supervisor")),
            ("rate_limit_auto_resume", meta_bool(id, "rate_limit_auto_resume")),
        ];
        let caps_lines: String = caps.iter()
            .map(|(k, v)| format!("{nl}            {k}: {v},"))
            .collect();

        out.push_str(&format!("impl HostProvider for {sn} {{"));
        out.push_str(&format!("{nl}    fn host_id(&self) -> &'static str {{ \"{id}\" }}"));
        out.push_str(&format!("{nl}    fn install_tool(&self) -> &'static str {{ \"{tool}\" }}"));
        out.push_str(&format!(
            "{nl}    fn capabilities(&self) -> HostCapabilities {{{nl}        HostCapabilities {{{nl}            mcp_config_key: \"{mcp}\",{nl}            transport_type: \"{trans}\",{nl}            config_path: \"{cfg}\",{caps_lines}{nl}            ..Default::default()\
             {nl}        }}{nl}    }}"
        ));
        // Build RegistryDispatcher initialization from registry fields
        let session_start = meta_bool(id, "session_start");
        let subagent_start = meta_bool(id, "subagent_start");
        let subagent_stop = meta_bool(id, "subagent_stop");
        let pretool_protection = meta_bool(id, "pretool_path_protection");
        let pretool_hint = meta_str(id, "pretool_entrypoint_hint");
        let scan_tool_input = meta_bool(id, "session_key_scan_tool_input");

        out.push_str(&format!(
            "{nl}    fn dispatcher(&self) -> Box<dyn super::hook_dispatch::HostHookDispatcher> {{\
             {nl}        Box::new(super::host_extensions::dispatch::RegistryDispatcher {{\
             {nl}            config: super::generic_config::GenericHostConfig {{\
             {nl}                id: \"{id}\",\
             {nl}                label: \"{label}\",\
             {nl}                state_dir: \".{id}\",\
             {nl}                session_start: {session_start},\
             {nl}                subagent_start: {subagent_start},\
             {nl}                subagent_stop: {subagent_stop},\
             {nl}                pretool_path_protection: {pretool_protection},\
             {nl}                pretool_entrypoint_hint: \"{pretool_hint}\",\
             {nl}                scan_tool_input: {scan_tool_input},\
             {nl}                ..super::generic_config::GenericHostConfig::new(\"{id}\", \"{label}\")\
             {nl}            }},\
             {nl}        }})\
             {nl}    }}",
            label = pascal(id)
        ));
        out.push_str(&format!("{nl}}}{nl}"));
    }

    // ── Registry ──
    let ids_literal: Vec<String> = supported.iter().map(|id| format!("\"{}\"", id)).collect();
    let push_body: String = supported.iter()
        .map(|id| format!("    providers.push(Box::new({}HostProvider));", pascal(id)))
        .collect::<Vec<_>>()
        .join("\n");

    out.push_str(&format!(
        "\n\
         #[allow(dead_code)]\n\
         pub(crate) const REGISTRY_SUPPORTED_HOST_IDS: &[&str] = &[{}];\n\n\
         pub(crate) fn push_registered_host_providers(\n\
         providers: &mut Vec<Box<dyn super::HostProvider>>,\n\
         ) {{\n\
         {push_body}\n\
         }}\n",
        ids_literal.join(", ")
    ));

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("generated_host_providers.rs"), out)
        .expect("write generated_host_providers.rs");
}
