//! Minimal build.rs for host-projection: generates host provider registration code.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let registry_path = manifest_dir
        .join("..")
        .join("..")
        .join("configs/framework/RUNTIME_REGISTRY.json");

    println!("cargo:rerun-if-changed={}", registry_path.display());

    let json_str = fs::read_to_string(&registry_path)
        .unwrap_or_else(|err| panic!("read {}: {err}", registry_path.display()));
    let reg: serde_json::Value =
        serde_json::from_str(&json_str).expect("parse RUNTIME_REGISTRY.json");

    let supported: Vec<String> = reg
        .get("host_targets")
        .expect("RUNTIME_REGISTRY missing host_targets")
        .get("supported")
        .and_then(serde_json::Value::as_array)
        .expect("host_targets.supported must be a non-empty array")
        .iter()
        .map(|v| {
            v.as_str()
                .map(str::trim)
                .filter(|s| !s.is_empty())
                .map(str::to_string)
                .expect("non-empty string")
        })
        .collect();

    let ids_literal = supported
        .iter()
        .map(|id| format!("\"{id}\""))
        .collect::<Vec<_>>()
        .join(", ");

    // Map host_id → (module, struct) for all providers living in host-projection.
    let host_provider_map: std::collections::HashMap<&str, (&str, &str)> = [
        ("cursor", ("cursor_provider", "CursorHostProvider")),
        ("codex", ("codex_provider", "CodexHostProvider")),
        ("claude-code", ("claude_provider", "ClaudeHostProvider")),
        ("opencode", ("opencode_provider", "OpencodeHostProvider")),
        ("mimo", ("mimo_provider", "MimoHostProvider")),
    ]
    .into_iter()
    .collect();

    let push_lines: Vec<String> = supported
        .iter()
        .filter_map(|id| {
            host_provider_map
                .get(id.as_str())
                .map(|(module, struct_name)| {
                    format!("    providers.push(Box::new(super::{module}::{struct_name}));")
                })
        })
        .collect();
    let push_body = push_lines.join("\n");

    let generated = format!(
        r#"// @generated by build.rs — do not edit
// source: configs/framework/RUNTIME_REGISTRY.json → host_targets.supported

#[allow(dead_code)]
pub(crate) const REGISTRY_SUPPORTED_HOST_IDS: &[&str] = &[{ids_literal}];

pub(crate) fn push_registered_host_providers(
    providers: &mut Vec<Box<dyn super::HostProvider>>,
) {{
{push_body}
}}
"#
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("generated_host_providers.rs"), generated)
        .expect("write generated_host_providers.rs");
}
