[package]
name = "routing-engine"
version = "0.1.0"
edition = "2024"
[lints]
workspace = true

[dependencies]
notify.workspace = true
rayon.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
insta.workspace = true
tempfile.workspace = true
