//! Compile-time checker registration generation for research-harness.
//!
//! Reads `configs/framework/RUNTIME_REGISTRY.json` → `quality_gate_checkers.registrations`,
//! filters for entries where `crate == "research-harness"`, and generates
//! `register_checkers_from_registry()`.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let registry_path = manifest_dir
        .join("..")
        .join("..")
        .join("configs/framework/RUNTIME_REGISTRY.json");

    println!("cargo:rerun-if-changed={}", registry_path.display());

    let json_str = fs::read_to_string(&registry_path)
        .unwrap_or_else(|err| panic!("read {}: {err}", registry_path.display()));

    // Allow building without the registry for isolated crate builds
    let reg: serde_json::Value = match serde_json::from_str(&json_str) {
        Ok(v) => v,
        Err(e) => {
            // If the JSON can't be parsed, generate an empty function and warn.
            // This can happen when building research-harness in isolation
            // (e.g., `cargo build -p research-harness`) from a different CWD.
            println!("cargo:warning=Cannot parse RUNTIME_REGISTRY.json: {e}");
            generate_empty_fn();
            return;
        }
    };

    let Some(checkers_section) = reg
        .get("quality_gate_checkers")
        .and_then(|v| v.get("registrations"))
        .and_then(serde_json::Value::as_array)
    else {
        println!("cargo:warning=No quality_gate_checkers.registrations in RUNTIME_REGISTRY.json");
        generate_empty_fn();
        return;
    };

    // Scene name → quality_gate::scene constant mapping
    let scene_consts: BTreeMap<&str, &str> = BTreeMap::from([
        ("general", "quality_gate::scene::GENERAL"),
        ("research", "quality_gate::scene::RESEARCH"),
        ("code_review", "quality_gate::scene::CODE_REVIEW"),
        ("slides", "quality_gate::scene::SLIDES"),
        ("visual", "quality_gate::scene::VISUAL"),
    ]);

    // Use BTreeSet to detect duplicates by (scene, type_name)
    let mut registrations: Vec<(&str, &str, &str)> = Vec::new();
    let mut seen = BTreeMap::new();

    for entry in checkers_section {
        let Some(entry) = entry.as_object() else {
            panic!("each quality_gate_checkers.registrations entry must be an object")
        };
        let crate_name = match entry.get("crate").and_then(serde_json::Value::as_str) {
            Some(c) => c,
            None => panic!("checker registration missing 'crate' field"),
        };
        if crate_name != "research-harness" {
            continue; // skip entries for other crates
        }
        let scene = entry
            .get("scene")
            .and_then(serde_json::Value::as_str)
            .unwrap_or_else(|| panic!("checker registration missing 'scene' field: {entry:?}"));
        let scene_const = scene_consts.get(scene).unwrap_or_else(|| {
            panic!("checker registration has invalid scene '{scene}'. Valid scenes: general, research, code_review, slides, visual")
        });
        let checker_type = entry
            .get("checker_type")
            .and_then(serde_json::Value::as_str)
            .unwrap_or_else(|| panic!("checker registration missing 'checker_type' field: {entry:?}"));
        let module_path = entry
            .get("checker_module")
            .and_then(serde_json::Value::as_str)
            .unwrap_or_else(|| {
                panic!("checker registration missing 'checker_module' field: {entry:?}")
            });

        let key = (scene, checker_type);
        if let Some(prev) = seen.get(&key) {
            panic!(
                "duplicate checker registration: scene='{scene}' checker_type='{checker_type}' \
                 (first seen at index {prev})"
            );
        }
        seen.insert(key, registrations.len());
        registrations.push((scene_const, module_path, checker_type));
    }

    if registrations.is_empty() {
        // This is OK if the research-harness crate is buildable without research
        // checkers — generate an empty function.
        generate_empty_fn();
        return;
    }

    let mut checker_reg_lines = String::new();
    for (scene_const, module_path, checker_type) in &registrations {
        checker_reg_lines.push_str(&format!(
            "    registry.register({scene_const},\n        Box::new(crate::{module_path}::{checker_type}));\n",
        ));
    }

    let generated = format!(
        r#"// @generated by build.rs — do not edit
// source: configs/framework/RUNTIME_REGISTRY.json → quality_gate_checkers.registrations (crate=research-harness)

pub fn register_checkers_from_registry(
    registry: &mut quality_gate::CheckerRegistry,
) {{
{checker_reg_lines}}}
"#
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("generated_research_checkers.rs"), &generated)
        .expect("write generated_research_checkers.rs");
}

fn generate_empty_fn() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let generated = r#"// @generated by build.rs — do not edit
// No research-harness checkers registered (empty build).

pub fn register_checkers_from_registry(
    _registry: &mut quality_gate::CheckerRegistry,
) {}
"#;
    fs::write(out_dir.join("generated_research_checkers.rs"), generated)
        .expect("write generated_research_checkers.rs");
}
