// Slide specification building and palette.


pub fn build_pptx_slide_specs(outline: &Value) -> Vec<PptxSlideSpec> {
    let content_slides = reflow_outline_slides(outline.get("slides").and_then(Value::as_array));
    let mut slides = Vec::new();
    slides.push(PptxSlideSpec {
        title: outline_str(outline, "title", "Untitled Deck").to_string(),
        subtitle: outline_str(outline, "subtitle", "").to_string(),
        label: "OPENING".to_string(),
        body: [
            outline_str(outline, "presenter", ""),
            outline_str(outline, "date", ""),
        ]
        .into_iter()
        .filter(|item| !item.is_empty())
        .map(str::to_string)
        .collect(),
        notes: notes_with_semantic_layout("cover", "Cover slide generated by the Rust ppt CLI."),
        layout: "cover",
    });

    for (idx, slide) in content_slides.iter().enumerate() {
        let mut body = value_string_array(slide, "bullets");
        if body.is_empty() {
            body = value_string_array(slide, "steps");
        }
        if body.is_empty() {
            body = value_string_array(slide, "timeline");
        }
        if body.is_empty() {
            body = comparison_body(slide);
        }
        if body.is_empty() {
            body = metrics_body(slide);
        }
        if body.is_empty() {
            body.push(outline_str(slide, "body", "").to_string());
        }
        body.retain(|item| !item.trim().is_empty());
        let pattern = detect_outline_pattern(slide);
        slides.push(PptxSlideSpec {
            title: outline_str(slide, "title", "").to_string(),
            subtitle: outline_str(slide, "subtitle", "").to_string(),
            label: format!("SECTION {:02}", idx + 1),
            notes: notes_with_semantic_layout(
                pattern,
                &format!(
                    "Slide {}: {}",
                    idx + 2,
                    outline_str(slide, "title", "Untitled")
                ),
            ),
            body,
            layout: pattern,
        });
    }

    slides.push(PptxSlideSpec {
        title: outline_str(outline, "closingText", "Thank you").to_string(),
        subtitle: String::new(),
        label: "FINAL SLIDE".to_string(),
        body: Vec::new(),
        notes: notes_with_semantic_layout("closing", "Closing slide generated by the Rust ppt CLI."),
        layout: "closing",
    });
    slides
}

pub fn comparison_body(slide: &Value) -> Vec<String> {
    let mut out = Vec::new();
    for side in ["left", "right"] {
        let value = slide
            .get("comparison")
            .and_then(|comparison| comparison.get(side))
            .unwrap_or(&Value::Null);
        let title = outline_str(value, "title", side);
        let items = value_string_array(value, "items").join("; ");
        if !items.is_empty() {
            out.push(format!("{title}: {items}"));
        }
    }
    out
}

pub fn metrics_body(slide: &Value) -> Vec<String> {
    slide
        .get("metrics")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .map(|metric| {
            format!(
                "{} {}",
                outline_str(metric, "value", ""),
                outline_str(metric, "label", "")
            )
            .trim()
            .to_string()
        })
        .filter(|item| !item.is_empty())
        .collect()
}

#[derive(Clone, Debug)]
pub struct PptPalette {
    stage: &'static str,
    panel: &'static str,
    panel_soft: &'static str,
    line: &'static str,
    glow: &'static str,
    text: &'static str,
    text_soft: &'static str,
    text_mute: &'static str,
}

pub fn ppt_palette(name: &str) -> PptPalette {
    match name {
        "light" => PptPalette {
            stage: "FAFAFA",
            panel: "FFFFFF",
            panel_soft: "F0F0F0",
            line: "E0E0E0",
            glow: "3B82F6",
            text: "1A1A1A",
            text_soft: "555555",
            text_mute: "777777",
        },
        "academic" => PptPalette {
            stage: "FFFFFF",
            panel: "FFFFFF",
            panel_soft: "E7E6E6",
            line: "E7E6E6",
            glow: "4874CB",
            text: "000000",
            text_soft: "44546A",
            text_mute: "888888",
        },
        _ => PptPalette {
            stage: "000000",
            panel: "111111",
            panel_soft: "171717",
            line: "2A2A2A",
            glow: "7EA9FF",
            text: "F2F2EE",
            text_soft: "B9B9B2",
            text_mute: "888883",
        },
    }
}
