// Extracted from lib.rs: yaml_parse.


pub fn read_outline(input: &Path) -> Result<Value> {
    let raw = fs::read_to_string(input)
        .with_context(|| format!("failed to read outline {}", input.display()))?;
    if has_extension(input, "json") {
        let value: Value = serde_json::from_str(&raw).context("failed to parse JSON outline")?;
        return Ok(unwrap_outline_plan(value));
    }
    parse_outline_yaml_subset(&raw)
}

pub fn unwrap_outline_plan(value: Value) -> Value {
    value
        .get("outline")
        .filter(|_| {
            value
                .get("format")
                .and_then(Value::as_str)
                .is_some_and(|format| format == "ppt-rust-outline-plan")
        })
        .cloned()
        .unwrap_or(value)
}

pub fn deck_template_from_outline(outline: &Value) -> DeckTemplate {
    let raw = outline
        .get("template")
        .or_else(|| outline.get("deck_template"))
        .and_then(Value::as_str)
        .map(str::trim)
        .unwrap_or("");
    match raw.to_ascii_lowercase().as_str() {
        "light" => DeckTemplate::Light,
        "corporate" | "academic" => DeckTemplate::Corporate,
        "dark" => DeckTemplate::Dark,
        _ => DeckTemplate::Dark,
    }
}

pub fn notes_with_semantic_layout(layout: &'static str, continuation: &str) -> String {
    format!(
        "rust_semantic_layout:{layout}\n{continuation}",
        layout = layout,
        continuation = continuation.trim_start()
    )
}

pub fn starter_outline_value(template: &DeckTemplate) -> Value {
    let palette = match template {
        DeckTemplate::Light => "light",
        DeckTemplate::Corporate => "academic",
        DeckTemplate::Dark => "dark",
    };
    let tmpl = match template {
        DeckTemplate::Light => "light",
        DeckTemplate::Corporate => "corporate",
        DeckTemplate::Dark => "dark",
    };
    json!({
        "title": "Rust Authored Deck",
        "subtitle": "Editable PPTX generated by Rust",
        "presenter": "Presenter",
        "date": "2026",
        "palette": palette,
        "template": tmpl,
        "slides": [
            {
                "title": "One Rust path",
                "subtitle": "Outline, PPTX writing, QA and inspection stay in the ppt CLI",
                "bullets": [
                    "Write outline JSON or YAML",
                    "Run ppt outline outline.json --build",
                    "Review rendered PNGs and QA output"
                ]
            }
        ],
        "closingText": "Thank you"
    })
}

pub fn parse_outline_yaml_subset(raw: &str) -> Result<Value> {
    let mut root = serde_json::Map::new();
    let mut slides = Vec::new();
    let mut current_slide: Option<serde_json::Map<String, Value>> = None;
    let mut current_list: Option<String> = None;
    let mut current_object: Option<String> = None;

    for line in raw.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        if !line.starts_with(' ') && trimmed.ends_with(':') {
            current_list = None;
            current_object = None;
            continue;
        }

        if !line.starts_with(' ') {
            if let Some((key, value)) = trimmed.split_once(':') {
                root.insert(key.trim().to_string(), parse_yaml_scalar(value.trim()));
            }
            continue;
        }

        if trimmed.starts_with("- ") && line.starts_with("  - ") {
            if let Some(slide) = current_slide.take() {
                slides.push(Value::Object(slide));
            }
            let mut slide = serde_json::Map::new();
            let rest = trimmed.trim_start_matches("- ").trim();
            if let Some((key, value)) = rest.split_once(':') {
                slide.insert(key.trim().to_string(), parse_yaml_scalar(value.trim()));
            }
            current_slide = Some(slide);
            current_list = None;
            current_object = None;
            continue;
        }

        let Some(slide) = current_slide.as_mut() else {
            continue;
        };

        if line.starts_with("        - ") {
            let Some(object_key) = current_object.clone() else {
                continue;
            };
            let item = trimmed.trim_start_matches("- ").trim();
            if let Some(object) = slide.get_mut(&object_key).and_then(Value::as_object_mut) {
                let array = object
                    .entry("series".to_string())
                    .or_insert_with(|| json!([]));
                if let Some(items) = array.as_array_mut() {
                    items.push(parse_yaml_inline_value(item));
                }
            }
            continue;
        }

        if line.starts_with("        ") {
            let object_key = current_object
                .clone()
                .or_else(|| current_list.clone())
                .unwrap_or_default();
            if object_key.is_empty() {
                continue;
            }
            if let Some((key, value)) = trimmed.split_once(':') {
                if let Some(object) = slide.get_mut(&object_key).and_then(Value::as_object_mut) {
                    object.insert(key.trim().to_string(), parse_yaml_scalar(value.trim()));
                }
            }
            continue;
        }

        if line.starts_with("    ") && !line.starts_with("      ") {
            if let Some((key, value)) = trimmed.split_once(':') {
                let key = key.trim().to_string();
                let value = value.trim();
                current_list = None;
                current_object = None;
                if value.is_empty() {
                    if matches!(key.as_str(), "bullets" | "metrics" | "steps" | "timeline") {
                        slide.insert(key.clone(), Value::Array(Vec::new()));
                        current_list = Some(key);
                    } else {
                        slide.insert(key.clone(), json!({}));
                        current_object = Some(key);
                    }
                } else if let Some(object_key) = current_object.clone() {
                    if let Some(object) = slide.get_mut(&object_key).and_then(Value::as_object_mut)
                    {
                        object.insert(key, parse_yaml_scalar(value));
                    }
                } else {
                    slide.insert(key, parse_yaml_scalar(value));
                    current_object = None;
                }
            }
            continue;
        }

        if line.starts_with("      - ") {
            let Some(list_key) = current_list.clone() else {
                continue;
            };
            let item = trimmed.trim_start_matches("- ").trim();
            if let Some(array) = slide.get_mut(&list_key).and_then(Value::as_array_mut) {
                array.push(parse_yaml_inline_value(item));
            }
            continue;
        }

        if line.starts_with("      ") && !line.starts_with("        ") {
            if let Some((raw_key, raw_value)) = trimmed.split_once(':') {
                let key = raw_key.trim().to_string();
                let value = raw_value.trim();
                if let Some(object_key) = current_object.clone() {
                    if let Some(object) = slide.get_mut(&object_key).and_then(Value::as_object_mut)
                    {
                        if value.is_empty() {
                            object.insert(key, json!([]));
                        } else {
                            object.insert(key, parse_yaml_scalar(value));
                        }
                    }
                } else if value.is_empty() {
                    slide.insert(key.clone(), json!({}));
                    current_object = Some(key);
                } else {
                    slide.insert(key, parse_yaml_scalar(value));
                    current_object = None;
                }
            }
            continue;
        }
    }

    if let Some(slide) = current_slide.take() {
        slides.push(Value::Object(slide));
    }
    root.insert("slides".to_string(), Value::Array(slides));
    Ok(Value::Object(root))
}

pub fn parse_yaml_inline_value(value: &str) -> Value {
    let value = value.trim();
    if value.starts_with('{') || value.starts_with('[') {
        parse_yaml_jsonish(value).unwrap_or_else(|| Value::String(unquote_yaml(value).to_string()))
    } else {
        parse_yaml_scalar(value)
    }
}

pub fn parse_yaml_scalar(value: &str) -> Value {
    let value = value.trim();
    if value.is_empty() {
        Value::Null
    } else if value.starts_with('[') {
        parse_yaml_jsonish(value).unwrap_or_else(|| Value::String(unquote_yaml(value).to_string()))
    } else {
        Value::String(unquote_yaml(value).to_string())
    }
}

pub fn parse_yaml_jsonish(value: &str) -> Option<Value> {
    serde_json::from_str(value)
        .ok()
        .or_else(|| serde_json::from_str(&yaml_inline_to_jsonish(value)).ok())
}

pub fn yaml_inline_to_jsonish(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 8);
    let mut in_string = false;
    let mut quote = '\0';
    let mut key_start = true;
    let mut reading_key = false;
    for ch in value.chars() {
        if in_string {
            if ch == quote {
                in_string = false;
            }
            out.push(ch);
            continue;
        }
        match ch {
            '"' | '\'' => {
                in_string = true;
                quote = ch;
                out.push('"');
            }
            '{' | ',' => {
                key_start = ch == '{';
                reading_key = false;
                out.push(ch);
            }
            ':' if reading_key => {
                key_start = false;
                reading_key = false;
                out.push_str("\":");
            }
            ch if key_start && !ch.is_whitespace() => {
                key_start = false;
                reading_key = true;
                out.push('"');
                out.push(ch);
            }
            _ => out.push(ch),
        }
    }
    out
}

pub fn unquote_yaml(value: &str) -> &str {
    value
        .strip_prefix('"')
        .and_then(|item| item.strip_suffix('"'))
        .or_else(|| {
            value
                .strip_prefix('\'')
                .and_then(|item| item.strip_suffix('\''))
        })
        .unwrap_or(value)
}

pub fn generate_outline_deck_source(outline: &Value, _template: &DeckTemplate) -> Result<String> {
    let outline = naturalize_outline_value(outline);
    serde_json::to_string_pretty(&json!({
        "format": "ppt-rust-outline-plan",
        "design_brief": {
            "source": "DESIGN.md visual contract when source materials or brand examples exist; otherwise choose a frontend-design direction before styling",
            "copy": "run built-in Rust copy naturalization before layout; use $copywriting for persuasive decks and $paper-writing for academic decks; keep direct claims and remove generic AI filler",
            "layout": "one visual lead, readable type, no equal-weight card farm; encode the chosen design roles in deck.plan.json",
            "audit": "render evidence, visual-review findings, design-md drift verdict, then strict Rust QA"
        },
        "outline": outline
    }))
    .context("failed to serialize Rust outline plan")
}

pub fn naturalize_outline_value(value: &Value) -> Value {
    match value {
        Value::String(text) => Value::String(naturalize_copy_text(text)),
        Value::Array(items) => Value::Array(items.iter().map(naturalize_outline_value).collect()),
        Value::Object(map) => Value::Object(
            map.iter()
                .map(|(key, value)| (key.clone(), naturalize_outline_value(value)))
                .collect(),
        ),
        _ => value.clone(),
    }
}
