//! Compile-time HostProvider registration from `RUNTIME_REGISTRY.json` → `host_targets.host_providers`.
//!
//! hosts/mod.rs is now a re-export shim from host-projection; we only validate
//! that RUNTIME_REGISTRY.json is readable and host_targets.supported is non-empty.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let registry_path = manifest_dir
        .join("..")
        .join("..")
        .join("configs/framework/RUNTIME_REGISTRY.json");
    let cargo_toml_path = manifest_dir.join("Cargo.toml");

    println!("cargo:rerun-if-changed={}", registry_path.display());
    println!("cargo:rerun-if-changed={}", cargo_toml_path.display());

    let json_str = fs::read_to_string(&registry_path)
        .unwrap_or_else(|err| panic!("read {}: {err}", registry_path.display()));
    let reg: serde_json::Value =
        serde_json::from_str(&json_str).expect("parse RUNTIME_REGISTRY.json");

    let cargo_toml = fs::read_to_string(&cargo_toml_path)
        .unwrap_or_else(|err| panic!("read {}: {err}", cargo_toml_path.display()));

    let host_targets = reg
        .get("host_targets")
        .expect("RUNTIME_REGISTRY missing host_targets");
    let supported: Vec<String> = host_targets
        .get("supported")
        .and_then(serde_json::Value::as_array)
        .expect("host_targets.supported must be a non-empty array")
        .iter()
        .map(|value| {
            value
                .as_str()
                .map(str::trim)
                .filter(|s| !s.is_empty())
                .map(str::to_string)
                .expect("host_targets.supported entries must be non-empty strings")
        })
        .collect();
    assert!(
        !supported.is_empty(),
        "host_targets.supported must not be empty"
    );

    let providers = host_targets
        .get("host_providers")
        .and_then(serde_json::Value::as_object)
        .expect("host_targets.host_providers must be an object");

    for host_id in &supported {
        if !providers.contains_key(host_id) {
            panic!(
                "host_targets.host_providers missing entry for supported host `{host_id}`"
            );
        }
    }
    for host_id in providers.keys() {
        if !supported.iter().any(|id| id == host_id) {
            panic!(
                "host_targets.host_providers has `{host_id}` which is not in host_targets.supported"
            );
        }
    }

    let mut pushes = String::new();
    for host_id in &supported {
        let entry = providers
            .get(host_id)
            .and_then(serde_json::Value::as_object)
            .unwrap_or_else(|| panic!("host_providers.{host_id} must be an object"));
        let feature = entry
            .get("cargo_feature")
            .and_then(serde_json::Value::as_str)
            .unwrap_or_else(|| panic!("host_providers.{host_id}.cargo_feature required"));
        let module = entry
            .get("provider_module")
            .and_then(serde_json::Value::as_str)
            .unwrap_or_else(|| panic!("host_providers.{host_id}.provider_module required"));
        let provider_type = entry
            .get("provider_type")
            .and_then(serde_json::Value::as_str)
            .unwrap_or_else(|| panic!("host_providers.{host_id}.provider_type required"));

        // Validate that Cargo.toml declares the required feature
        if !cargo_toml_declares_feature(&cargo_toml, feature) {
            panic!(
                "host_providers.{host_id}: Cargo.toml [features] missing `{feature}`; \
                 add it manually (features are not generated from RUNTIME_REGISTRY.json)"
            );
        }

        pushes.push_str(&format!(
            "    #[cfg(feature = \"{feature}\")]\n    providers.push(Box::new(super::{module}::{provider_type}));\n"
        ));
    }

    let ids_literal = supported
        .iter()
        .map(|id| format!("\"{id}\""))
        .collect::<Vec<_>>()
        .join(", ");

    let generated = format!(
        r#"// @generated by build.rs — do not edit
// source: configs/framework/RUNTIME_REGISTRY.json → host_targets.host_providers

pub(crate) const REGISTRY_SUPPORTED_HOST_IDS: &[&str] = &[{ids_literal}];

pub(crate) fn push_registered_host_providers(
    providers: &mut Vec<Box<dyn super::HostProvider>>,
) {{
{pushes}}}
"#
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("generated_host_providers.rs"), generated)
        .expect("write generated_host_providers.rs");
}

fn cargo_toml_declares_feature(cargo_toml: &str, feature: &str) -> bool {
    let needle = format!("{feature} =");
    cargo_toml
        .lines()
        .any(|line| line.trim().starts_with(&needle))
}
